services:
  - type: web
    name: downloader-backend
    env: node
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PATH
        value: /usr/local/bin:/usr/bin:$PATH
