#!/bin/bash
set -e

echo "🔧 Starting render-build.sh..."

# Define binary install location
BIN_DIR="$HOME/bin"

# Create a safe binary directory in the user's home
echo "📁 Creating $BIN_DIR..."
mkdir -p "$BIN_DIR"
chmod 755 "$BIN_DIR"

# Download the latest yt-dlp binary from GitHub
echo "⬇️ Downloading yt-dlp..."

# Try GitHub URL first
if ! curl -L -f -S --retry 3 --retry-delay 3 https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o "$BIN_DIR/yt-dlp"; then
  echo "⚠️ GitHub download failed, trying fallback URL..."
  # Try fallback URL
  curl -L -f -S --retry 3 --retry-delay 3 https://yt-dlp.org/latest/yt-dlp -o "$BIN_DIR/yt-dlp"
fi

# Make it executable
chmod +x "$BIN_DIR/yt-dlp"
echo "✅ yt-dlp downloaded and made executable."

# Add the bin directory to PATH
export PATH="$BIN_DIR:$PATH"
echo "export PATH=$BIN_DIR:$PATH" >> ~/.bashrc

# Create temp directory
echo "📁 Creating temp directory..."
mkdir -p "./temp"
chmod 755 "./temp"

# Create node_modules/.bin directory if it doesn't exist
echo "📁 Creating node_modules/.bin directory..."
mkdir -p "./node_modules/.bin"

# Create node_modules/yt-dlp-exec/bin directory if it doesn't exist
echo "📁 Creating node_modules/yt-dlp-exec/bin directory..."
mkdir -p "./node_modules/yt-dlp-exec/bin"

# Create symlinks to yt-dlp in various locations
echo "🔗 Creating symlinks to yt-dlp..."
ln -sf "$BIN_DIR/yt-dlp" "./node_modules/.bin/yt-dlp"
ln -sf "$BIN_DIR/yt-dlp" "./node_modules/yt-dlp-exec/bin/yt-dlp"
ln -sf "$BIN_DIR/yt-dlp" "./yt-dlp"

# Try to create a symlink in /usr/local/bin if possible (might require sudo)
if [ -w "/usr/local/bin" ]; then
  echo "📁 Creating symlink in /usr/local/bin..."
  ln -sf "$BIN_DIR/yt-dlp" "/usr/local/bin/yt-dlp"
fi

# Verify installations
echo "🔍 Verifying installations..."
which yt-dlp || echo "⚠️ yt-dlp not found in PATH"
ls -la "./node_modules/.bin/yt-dlp" || echo "⚠️ Symlink in node_modules/.bin not created"
ls -la "./node_modules/yt-dlp-exec/bin/yt-dlp" || echo "⚠️ Symlink in node_modules/yt-dlp-exec/bin not created"

# Check if youtube-cookies.txt exists, create a placeholder if it doesn't
echo "🔍 Checking for youtube-cookies.txt..."
if [ ! -f "./youtube-cookies.txt" ]; then
  echo "⚠️ youtube-cookies.txt not found, creating placeholder..."
  cat > ./youtube-cookies.txt << 'EOL'
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.
# This file is used for YouTube authentication
# Format: domain_name TRUE|FALSE path secure expiry name value
.youtube.com	TRUE	/	FALSE	0	YSC	placeholder
.youtube.com	TRUE	/	TRUE	0	CONSENT	placeholder
.youtube.com	TRUE	/	FALSE	0	LOGIN_INFO	placeholder
.youtube.com	TRUE	/	FALSE	0	SID	placeholder
.youtube.com	TRUE	/	FALSE	0	__Secure-1PSID	placeholder
.youtube.com	TRUE	/	FALSE	0	__Secure-3PSID	placeholder
.youtube.com	TRUE	/	FALSE	0	SSID	placeholder
.youtube.com	TRUE	/	FALSE	0	AECHID	placeholder
.youtube.com	TRUE	/	FALSE	0	SAPISID	placeholder
.youtube.com	TRUE	/	FALSE	0	__Secure-1PSIDTS	placeholder
.youtube.com	TRUE	/	FALSE	0	__Secure-3PSIDTS	placeholder
EOL
  chmod 644 ./youtube-cookies.txt
  echo "✅ Created comprehensive placeholder youtube-cookies.txt with authentication cookies"
else
  echo "✅ youtube-cookies.txt already exists"
fi

echo "✅ Build script completed successfully."
