services:
  - type: web
    name: downloader-backend
    env: node
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
      apt-get update && apt-get install -y ffmpeg
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: temp
      mountPath: /opt/render/project/src/temp
      sizeGB: 1
