services:
  - type: web
    name: downloader-backend
    env: node
    buildCommand: |
      pip install yt-dlp
      chmod +x "$(which yt-dlp)"
      npm install
    startCommand: npm start
    rootDir: server
