services:
  - type: web
    name: downloader-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    build:
      env:
        PUPPETEER_SKIP_DOWNLOAD: "true"
    environment:
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
